image: node:latest

pages:
  stage: deploy
  script:
   - npm install -g gulp
   - npm install
   - gulp
  artifacts:
    paths:
    - public
  environment:
    name: production/pages
    url: http://veganeats.recipes/

  only:
  - master
