image: node:latest

pages:
  stage: deploy
  script:
   - npm install -g gulp
   - npm install
   - gulp
   - mkdir newPublicFolder
   - mv public/* newPublicFolder
  artifacts:
    paths:
    - newPublicFolder
  only:
  - master
