image: node:latest

pages:
  stage: deploy
  script:
   - npm install -g gulp
   - npm install
   - gulp
   - mkdir public
   - mv public/* public
  artifacts:
    paths:
    - public
  only:
  - master
