image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  - npm install

stages:
  - build_deploy

build_&_deploy_app:
  stage: build_deploy
    script:
    - gulp
    artifacts:
      paths:
      - vendor
  only:
   - master
